name: Waka Readme

on:
  # For manual workflow trigger
  workflow_dispatch:
  schedule:
    # Runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # This action name
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master # Do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Required
          ### Meta
          API_BASE_URL: https://wakatime.com/api # Optional, can be omitted if default is fine
          REPOSITORY: https://github.com/Hieronius/Hieronius # Optional, specify if you want to track a specific repo
          ### Content
          SHOW_TITLE: true # Optional
          SECTION_NAME: waka # Optional, ensure this is what you want to display in your README
          BLOCKS: '' # Optional, specify blocks if needed; currently set to empty string to avoid syntax errors
          CODE_LANG: rust # Optional, specify the language you want to track; remove if not needed
          TIME_RANGE: all_time # Optional, can be 'last_7_days', 'last_30_days', etc.
          LANG_COUNT: 10 # Optional, specify how many languages to show; adjust as needed
          SHOW_TIME: true # Optional
          SHOW_TOTAL: true # Optional
          SHOW_MASKED_TIME: false # Optional
          STOP_AT_OTHER: true # Optional, set to false if you want to include other languages not specified in IGNORED_LANGUAGES
          IGNORED_LANGUAGES: YAML JSON TOML # Optional, specify languages to ignore; ensure this list is correct and formatted properly
          ### Commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # Optional, customize as needed
          TARGET_BRANCH: Main # Optional, change if your default branch is named differently (e.g., main)
          TARGET_PATH: README.md # Optional, specify the path where the stats should be updated; default is README.md
          COMMITTER_NAME: GitHubActionBot # Optional, customize as needed
          COMMITTER_EMAIL: action-bot@github.com # Optional, customize as needed
          AUTHOR_NAME: YOUR_NAME # Optional, replace with your name or leave it out if not needed
          AUTHOR_EMAIL: YOUR@EMAIL.com # Optional, replace with your email or use secrets for privacy
